### ISSUE TITLE
python -V ?

### ISSUE THREAD

**Issue by 1iwl** [yaphone/RasNeteaseMusic#1]
# python run.py 
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from WxNeteaseMusic import WxNeteaseMusic
  File "/root/software/WxNeteaseMusic/WxNeteaseMusic.py", line 2, in <module>
    import itchat
  File "/root/software/WxNeteaseMusic/itchat/__init__.py", line 2, in <module>
    from .core import Core
  File "/root/software/WxNeteaseMusic/itchat/core.py", line 3, in <module>
    import requests
ImportError: No module named requests

**Comment by yaphone** [comment]
2.7.x，这里应该是缺少request包吧，pip install request

**Comment by yaphone** [comment]
pip install requests

**Comment by 1iwl** [comment]
thanks!!
